import PDFDocument from "pdfkit";
import type { AnalysisLean } from "../models/analysis.model.js";
import { drawText, registerFonts } from "./pdfFonts.js";

function drawReport(doc: PDFKit.PDFDocument, analysis: AnalysisLean): void {
  const gradient: [number, number, number] = [99, 102, 241];

  doc.rect(0, 0, doc.page.width, 130).fill(gradient);
  doc
    .fillColor("#FFFFFF")
    .font("Helvetica-Bold")
    .fontSize(26)
    .text("ClearView AI — Website Report", 56, 40);
  doc
    .font("Helvetica")
    .fontSize(12)
    .text(`Analyzed on ${analysis.createdAt.toISOString().slice(0, 10)}`, 56, 78);

  doc.y = 170;

  const sectionTitle = (title: string) => {
    doc.fillColor(gradient).font("Helvetica-Bold").fontSize(15);
    doc.text(title, 56, doc.y);
    doc.moveDown(0.6);
  };

  const body = (text: string, width = 460) => {
    doc.fillColor("#1F2937");
    drawText(doc, text, 56, doc.y, width, 11);
    doc.moveDown(0.7);
  };

  const bullet = (text: string) => {
    doc.fillColor("#1F2937");
    drawText(doc, `•  ${text}`, 66, doc.y, 440, 10.5);
    doc.moveDown(0.55);
  };

  sectionTitle("Website");
  body(`${analysis.url} — ${analysis.title || "Untitled"}`);

  sectionTitle("Readability");
  body(`Score: ${analysis.readabilityScore}/100  •  Grade: ${analysis.readabilityGrade}`);

  sectionTitle("Clutter Detection");
  body(`Score: ${analysis.clutterScore}/100 (higher = more clutter)`);
  if (analysis.clutterIssues.length > 0) {
    analysis.clutterIssues.forEach(bullet);
  } else {
    body("No significant clutter issues detected.");
  }

  sectionTitle("Cognitive Load");
  body(
    `Score: ${analysis.cognitiveLoad.score}/100  •  Level: ${analysis.cognitiveLoad.level}`
  );

  sectionTitle("AI Summary");
  body(analysis.summary.text);

  sectionTitle("Key Insights");
  analysis.summary.keyInsights.forEach(bullet);

  sectionTitle("Recommendations");
  analysis.recommendations.forEach(bullet);

  doc
    .fillColor("#9CA3AF")
    .font("Helvetica")
    .fontSize(9)
    .text(
      "Generated by ClearView AI — AI website analysis in seconds.",
      56,
      doc.page.height - 50
    );
}

export async function generatePdfReport(analysis: AnalysisLean): Promise<Buffer> {
  const doc = new PDFDocument({
    size: "A4",
    margins: { top: 150, bottom: 70, left: 56, right: 56 },
    bufferPages: true,
  });
  registerFonts(doc);

  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));

  return new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    drawReport(doc, analysis);
    doc.end();
  });
}
